# Generated by Django 5.0.3 on 2024-03-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fishname', models.CharField(max_length=20)),
                ('fprice', models.IntegerField()),
                ('fstock', models.IntegerField()),
                ('fimage', models.FileField(upload_to='')),
            ],
        ),
    ]
