# Generated by Django 5.0.3 on 2024-04-04 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapps.fish')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapps.register')),
            ],
        ),
    ]
