# Generated by Django 5.0.3 on 2024-04-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
