# Generated by Django 5.0.3 on 2024-04-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0007_alter_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
