# Generated by Django 5.0.3 on 2024-04-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0008_fish_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='quantity',
            new_name='fquantity',
        ),
    ]
