# Generated by Django 5.0.3 on 2024-04-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0009_rename_quantity_fish_fquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='fquantity',
        ),
        migrations.AlterField(
            model_name='fish',
            name='fstock',
            field=models.IntegerField(default=1),
        ),
    ]
