# Generated by Django 5.0.3 on 2024-04-24 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0010_remove_fish_fquantity_alter_fish_fstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliverydetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapps.fish')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapps.register')),
            ],
        ),
    ]
