# Generated by Django 5.0.3 on 2024-04-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0011_deliverydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
