# Generated by Django 5.0.3 on 2024-05-02 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0012_fish_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deliverydetails',
        ),
    ]
