# Generated by Django 5.0.3 on 2024-05-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0014_deliverydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='in', max_length=10),
        ),
    ]
