# Generated by Django 5.0.3 on 2024-05-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0015_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='fquantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
