# Generated by Django 5.0.3 on 2024-05-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0016_fish_fquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='payment_status',
            field=models.CharField(default='PAID', max_length=20, null=True),
        ),
    ]
